# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - builder: "rust"
    binary: "cli"
    flags:
      - "--release"
      - "-p=cli"
    targets:
      - "aarch64-unknown-linux-gnu"

source:
  enabled: false

dockers_v2:
  - ids:
      - "fennec"
    platforms:
      - "linux/arm64"
    images:
      - "ghcr.io/eigenein/fennec"
    tags:
      - "latest"
      - "{{ .Version }}"
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"

docker_signs:
  - cmd: "cosign"
    args:
      - "sign"
      - "${artifact}"
      - "--yes"
    artifacts: "all"
