pub mod read_coils;
pub mod read_discrete_inputs;
pub mod read_exception_status;
pub mod read_holding_registers;
pub mod read_input_registers;
pub mod write_multiple_coils;
pub mod write_multiple_registers;
pub mod write_single_coil;
pub mod write_single_register;
