name: 🧪 Check

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - "README.md"
      - ".dockerignore"
      - ".gitignore"
      - "renovate.json"
      - "rustfmt.toml"
      - ".goreleaser.yaml"
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: "always"
  SCCACHE_GHA_ENABLED: "true"

jobs:
  check:
    name: 🧪 Check
    runs-on: ubuntu-latest

    steps:
      - name: ⬆️ Set up stable Rust
        uses: "dtolnay/rust-toolchain@stable"
        with:
          components: "clippy"

      - name: ⬆️ Set up nightly Rust
        uses: "dtolnay/rust-toolchain@nightly"
        with:
          components: "llvm-tools-preview"

      - name: "📥 Checkout"
        uses: "actions/checkout@v6"

      - name: "⚡️ Rust Cache"
        uses: "Swatinem/rust-cache@v2"
        with:
          cache-on-failure: true

      - name: 🧪 Install coverage tools
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: "🧪 Test"
        run: "cargo +nightly llvm-cov --codecov --doctests --output-path=codecov.json --workspace -- --include-ignored"
        env:
          TZ: "Europe/Amsterdam"

      - name: "📝 Docs"
        run: "cargo doc --no-deps --lib"
        env:
          RUSTDOCFLAGS: "-D warnings"

      - name: 📤 Upload coverage
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: eigenein/fennec
          files: codecov.json

      - name: 💬 Clippy
        uses: giraffate/clippy-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --workspace --all-targets
          reporter: github-check
        continue-on-error: true
