name: "🧙 Code review"
on:
  pull_request:
    types: ["opened", "synchronize"]
jobs:
  review:
    runs-on: "ubuntu-slim"
    permissions:
      actions: "read"
      contents: "read"
      pull-requests: "write"
      issues: "write"
      id-token: "write"
    steps:
      - name: "📥 Checkout"
        uses: "actions/checkout@v7"
        with:
          fetch-depth: 1

      - uses: "anthropics/claude-code-action@v1"
        name: "🧙 Claude"
        continue-on-error: true
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          track_progress: true
          use_sticky_comment: true
          claude_args: "--model claude-haiku-4-5"
          plugin_marketplaces: "https://github.com/anthropics/claude-code.git"
          plugins: "code-review@claude-code-plugins"
          prompt: "/code-review:code-review ${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
